version: '3.7'
services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_HOST: ${DB_HOST}
    ports:
      - "5432:5432"
    networks:
      - orders-network

  app:
    build: .
    depends_on:
      - db
    env_file:
      - .env.development
    volumes:
      - .:/app
      - /c/Users/zuckw/.aws:/root/.aws:ro
    command: ["sh", "-c", "go run cmd/main.go"]
    ports:
      - "8080:8080"
    networks:
      - orders-network

networks:
  orders-network:
